# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Predefined image classes for image classification model."""

CLASSES = (
    ('background',),  # index=0
    ('tench', 'Tinca tinca'),  # index=1
    ('goldfish', 'Carassius auratus'),  # index=2
    ('great white shark', 'white shark', 'man-eater', 'man-eating shark',
     'Carcharodon carcharias'),  # index=3
    ('tiger shark', 'Galeocerdo cuvieri'),  # index=4
    ('hammerhead', 'hammerhead shark'),  # index=5
    ('electric ray', 'crampfish', 'numbfish', 'torpedo'),  # index=6
    ('stingray',),  # index=7
    ('cock',),  # index=8
    ('hen',),  # index=9
    ('ostrich', 'Struthio camelus'),  # index=10
    ('brambling', 'Fringilla montifringilla'),  # index=11
    ('goldfinch', 'Carduelis carduelis'),  # index=12
    ('house finch', 'linnet', 'Carpodacus mexicanus'),  # index=13
    ('junco', 'snowbird'),  # index=14
    ('indigo bunting', 'indigo finch', 'indigo bird',
     'Passerina cyanea'),  # index=15
    ('robin', 'American robin', 'Turdus migratorius'),  # index=16
    ('bulbul',),  # index=17
    ('jay',),  # index=18
    ('magpie',),  # index=19
    ('chickadee',),  # index=20
    ('water ouzel', 'dipper'),  # index=21
    ('kite',),  # index=22
    ('bald eagle', 'American eagle', 'Haliaeetus leucocephalus'),  # index=23
    ('vulture',),  # index=24
    ('great grey owl', 'great gray owl', 'Strix nebulosa'),  # index=25
    ('European fire salamander', 'Salamandra salamandra'),  # index=26
    ('common newt', 'Triturus vulgaris'),  # index=27
    ('eft',),  # index=28
    ('spotted salamander', 'Ambystoma maculatum'),  # index=29
    ('axolotl', 'mud puppy', 'Ambystoma mexicanum'),  # index=30
    ('bullfrog', 'Rana catesbeiana'),  # index=31
    ('tree frog', 'tree-frog'),  # index=32
    ('tailed frog', 'bell toad', 'ribbed toad', 'tailed toad',
     'Ascaphus trui'),  # index=33
    ('loggerhead', 'loggerhead turtle', 'Caretta caretta'),  # index=34
    ('leatherback turtle', 'leatherback', 'leathery turtle',
     'Dermochelys coriacea'),  # index=35
    ('mud turtle',),  # index=36
    ('terrapin',),  # index=37
    ('box turtle', 'box tortoise'),  # index=38
    ('banded gecko',),  # index=39
    ('common iguana', 'iguana', 'Iguana iguana'),  # index=40
    ('American chameleon', 'anole', 'Anolis carolinensis'),  # index=41
    ('whiptail', 'whiptail lizard'),  # index=42
    ('agama',),  # index=43
    ('frilled lizard', 'Chlamydosaurus kingi'),  # index=44
    ('alligator lizard',),  # index=45
    ('Gila monster', 'Heloderma suspectum'),  # index=46
    ('green lizard', 'Lacerta viridis'),  # index=47
    ('African chameleon', 'Chamaeleo chamaeleon'),  # index=48
    ('Komodo dragon', 'Komodo lizard', 'dragon lizard', 'giant lizard',
     'Varanus komodoensis'),  # index=49
    ('African crocodile', 'Nile crocodile', 'Crocodylus niloticus'),  # index=50
    ('American alligator', 'Alligator mississipiensis'),  # index=51
    ('triceratops',),  # index=52
    ('thunder snake', 'worm snake', 'Carphophis amoenus'),  # index=53
    ('ringneck snake', 'ring-necked snake', 'ring snake'),  # index=54
    ('hognose snake', 'puff adder', 'sand viper'),  # index=55
    ('green snake', 'grass snake'),  # index=56
    ('king snake', 'kingsnake'),  # index=57
    ('garter snake', 'grass snake'),  # index=58
    ('water snake',),  # index=59
    ('vine snake',),  # index=60
    ('night snake', 'Hypsiglena torquata'),  # index=61
    ('boa constrictor', 'Constrictor constrictor'),  # index=62
    ('rock python', 'rock snake', 'Python sebae'),  # index=63
    ('Indian cobra', 'Naja naja'),  # index=64
    ('green mamba',),  # index=65
    ('sea snake',),  # index=66
    ('horned viper', 'cerastes', 'sand viper', 'horned asp',
     'Cerastes cornutus'),  # index=67
    ('diamondback', 'diamondback rattlesnake',
     'Crotalus adamanteus'),  # index=68
    ('sidewinder', 'horned rattlesnake', 'Crotalus cerastes'),  # index=69
    ('trilobite',),  # index=70
    ('harvestman', 'daddy longlegs', 'Phalangium opilio'),  # index=71
    ('scorpion',),  # index=72
    ('black and gold garden spider', 'Argiope aurantia'),  # index=73
    ('barn spider', 'Araneus cavaticus'),  # index=74
    ('garden spider', 'Aranea diademata'),  # index=75
    ('black widow', 'Latrodectus mactans'),  # index=76
    ('tarantula',),  # index=77
    ('wolf spider', 'hunting spider'),  # index=78
    ('tick',),  # index=79
    ('centipede',),  # index=80
    ('black grouse',),  # index=81
    ('ptarmigan',),  # index=82
    ('ruffed grouse', 'partridge', 'Bonasa umbellus'),  # index=83
    ('prairie chicken', 'prairie grouse', 'prairie fowl'),  # index=84
    ('peacock',),  # index=85
    ('quail',),  # index=86
    ('partridge',),  # index=87
    ('African grey', 'African gray', 'Psittacus erithacus'),  # index=88
    ('macaw',),  # index=89
    ('sulphur-crested cockatoo', 'Kakatoe galerita',
     'Cacatua galerita'),  # index=90
    ('lorikeet',),  # index=91
    ('coucal',),  # index=92
    ('bee eater',),  # index=93
    ('hornbill',),  # index=94
    ('hummingbird',),  # index=95
    ('jacamar',),  # index=96
    ('toucan',),  # index=97
    ('drake',),  # index=98
    ('red-breasted merganser', 'Mergus serrator'),  # index=99
    ('goose',),  # index=100
    ('black swan', 'Cygnus atratus'),  # index=101
    ('tusker',),  # index=102
    ('echidna', 'spiny anteater', 'anteater'),  # index=103
    ('platypus', 'duckbill', 'duckbilled platypus', 'duck-billed platypus',
     'Ornithorhynchus anatinus'),  # index=104
    ('wallaby', 'brush kangaroo'),  # index=105
    ('koala', 'koala bear', 'kangaroo bear', 'native bear',
     'Phascolarctos cinereus'),  # index=106
    ('wombat',),  # index=107
    ('jellyfish',),  # index=108
    ('sea anemone', 'anemone'),  # index=109
    ('brain coral',),  # index=110
    ('flatworm', 'platyhelminth'),  # index=111
    ('nematode', 'nematode worm', 'roundworm'),  # index=112
    ('conch',),  # index=113
    ('snail',),  # index=114
    ('slug',),  # index=115
    ('sea slug', 'nudibranch'),  # index=116
    ('chiton', 'coat-of-mail shell', 'sea cradle',
     'polyplacophore'),  # index=117
    ('chambered nautilus', 'pearly nautilus', 'nautilus'),  # index=118
    ('Dungeness crab', 'Cancer magister'),  # index=119
    ('rock crab', 'Cancer irroratus'),  # index=120
    ('fiddler crab',),  # index=121
    ('king crab', 'Alaska crab', 'Alaskan king crab', 'Alaska king crab',
     'Paralithodes camtschatica'),  # index=122
    ('American lobster', 'Northern lobster', 'Maine lobster',
     'Homarus americanus'),  # index=123
    ('spiny lobster', 'langouste', 'rock lobster', 'crawfish', 'crayfish',
     'sea crawfish'),  # index=124
    ('crayfish', 'crawfish', 'crawdad', 'crawdaddy'),  # index=125
    ('hermit crab',),  # index=126
    ('isopod',),  # index=127
    ('white stork', 'Ciconia ciconia'),  # index=128
    ('black stork', 'Ciconia nigra'),  # index=129
    ('spoonbill',),  # index=130
    ('flamingo',),  # index=131
    ('little blue heron', 'Egretta caerulea'),  # index=132
    ('American egret', 'great white heron', 'Egretta albus'),  # index=133
    ('bittern',),  # index=134
    ('crane',),  # index=135
    ('limpkin', 'Aramus pictus'),  # index=136
    ('European gallinule', 'Porphyrio porphyrio'),  # index=137
    ('American coot', 'marsh hen', 'mud hen', 'water hen',
     'Fulica americana'),  # index=138
    ('bustard',),  # index=139
    ('ruddy turnstone', 'Arenaria interpres'),  # index=140
    ('red-backed sandpiper', 'dunlin', 'Erolia alpina'),  # index=141
    ('redshank', 'Tringa totanus'),  # index=142
    ('dowitcher',),  # index=143
    ('oystercatcher', 'oyster catcher'),  # index=144
    ('pelican',),  # index=145
    ('king penguin', 'Aptenodytes patagonica'),  # index=146
    ('albatross', 'mollymawk'),  # index=147
    ('grey whale', 'gray whale', 'devilfish', 'Eschrichtius gibbosus',
     'Eschrichtius robustus'),  # index=148
    ('killer whale', 'killer', 'orca', 'grampus', 'sea wolf',
     'Orcinus orca'),  # index=149
    ('dugong', 'Dugong dugon'),  # index=150
    ('sea lion',),  # index=151
    ('Chihuahua',),  # index=152
    ('Japanese spaniel',),  # index=153
    ('Maltese dog', 'Maltese terrier', 'Maltese'),  # index=154
    ('Pekinese', 'Pekingese', 'Peke'),  # index=155
    ('Shih-Tzu',),  # index=156
    ('Blenheim spaniel',),  # index=157
    ('papillon',),  # index=158
    ('toy terrier',),  # index=159
    ('Rhodesian ridgeback',),  # index=160
    ('Afghan hound', 'Afghan'),  # index=161
    ('basset', 'basset hound'),  # index=162
    ('beagle',),  # index=163
    ('bloodhound', 'sleuthhound'),  # index=164
    ('bluetick',),  # index=165
    ('black-and-tan coonhound',),  # index=166
    ('Walker hound', 'Walker foxhound'),  # index=167
    ('English foxhound',),  # index=168
    ('redbone',),  # index=169
    ('borzoi', 'Russian wolfhound'),  # index=170
    ('Irish wolfhound',),  # index=171
    ('Italian greyhound',),  # index=172
    ('whippet',),  # index=173
    ('Ibizan hound', 'Ibizan Podenco'),  # index=174
    ('Norwegian elkhound', 'elkhound'),  # index=175
    ('otterhound', 'otter hound'),  # index=176
    ('Saluki', 'gazelle hound'),  # index=177
    ('Scottish deerhound', 'deerhound'),  # index=178
    ('Weimaraner',),  # index=179
    ('Staffordshire bullterrier', 'Staffordshire bull terrier'),  # index=180
    ('American Staffordshire terrier', 'Staffordshire terrier',
     'American pit bull terrier', 'pit bull terrier'),  # index=181
    ('Bedlington terrier',),  # index=182
    ('Border terrier',),  # index=183
    ('Kerry blue terrier',),  # index=184
    ('Irish terrier',),  # index=185
    ('Norfolk terrier',),  # index=186
    ('Norwich terrier',),  # index=187
    ('Yorkshire terrier',),  # index=188
    ('wire-haired fox terrier',),  # index=189
    ('Lakeland terrier',),  # index=190
    ('Sealyham terrier', 'Sealyham'),  # index=191
    ('Airedale', 'Airedale terrier'),  # index=192
    ('cairn', 'cairn terrier'),  # index=193
    ('Australian terrier',),  # index=194
    ('Dandie Dinmont', 'Dandie Dinmont terrier'),  # index=195
    ('Boston bull', 'Boston terrier'),  # index=196
    ('miniature schnauzer',),  # index=197
    ('giant schnauzer',),  # index=198
    ('standard schnauzer',),  # index=199
    ('Scotch terrier', 'Scottish terrier', 'Scottie'),  # index=200
    ('Tibetan terrier', 'chrysanthemum dog'),  # index=201
    ('silky terrier', 'Sydney silky'),  # index=202
    ('soft-coated wheaten terrier',),  # index=203
    ('West Highland white terrier',),  # index=204
    ('Lhasa', 'Lhasa apso'),  # index=205
    ('flat-coated retriever',),  # index=206
    ('curly-coated retriever',),  # index=207
    ('golden retriever',),  # index=208
    ('Labrador retriever',),  # index=209
    ('Chesapeake Bay retriever',),  # index=210
    ('German short-haired pointer',),  # index=211
    ('vizsla', 'Hungarian pointer'),  # index=212
    ('English setter',),  # index=213
    ('Irish setter', 'red setter'),  # index=214
    ('Gordon setter',),  # index=215
    ('Brittany spaniel',),  # index=216
    ('clumber', 'clumber spaniel'),  # index=217
    ('English springer', 'English springer spaniel'),  # index=218
    ('Welsh springer spaniel',),  # index=219
    ('cocker spaniel', 'English cocker spaniel', 'cocker'),  # index=220
    ('Sussex spaniel',),  # index=221
    ('Irish water spaniel',),  # index=222
    ('kuvasz',),  # index=223
    ('schipperke',),  # index=224
    ('groenendael',),  # index=225
    ('malinois',),  # index=226
    ('briard',),  # index=227
    ('kelpie',),  # index=228
    ('komondor',),  # index=229
    ('Old English sheepdog', 'bobtail'),  # index=230
    ('Shetland sheepdog', 'Shetland sheep dog', 'Shetland'),  # index=231
    ('collie',),  # index=232
    ('Border collie',),  # index=233
    ('Bouvier des Flandres', 'Bouviers des Flandres'),  # index=234
    ('Rottweiler',),  # index=235
    ('German shepherd', 'German shepherd dog', 'German police dog',
     'alsatian'),  # index=236
    ('Doberman', 'Doberman pinscher'),  # index=237
    ('miniature pinscher',),  # index=238
    ('Greater Swiss Mountain dog',),  # index=239
    ('Bernese mountain dog',),  # index=240
    ('Appenzeller',),  # index=241
    ('EntleBucher',),  # index=242
    ('boxer',),  # index=243
    ('bull mastiff',),  # index=244
    ('Tibetan mastiff',),  # index=245
    ('French bulldog',),  # index=246
    ('Great Dane',),  # index=247
    ('Saint Bernard', 'St Bernard'),  # index=248
    ('Eskimo dog', 'husky'),  # index=249
    ('malamute', 'malemute', 'Alaskan malamute'),  # index=250
    ('Siberian husky',),  # index=251
    ('dalmatian', 'coach dog', 'carriage dog'),  # index=252
    ('affenpinscher', 'monkey pinscher', 'monkey dog'),  # index=253
    ('basenji',),  # index=254
    ('pug', 'pug-dog'),  # index=255
    ('Leonberg',),  # index=256
    ('Newfoundland', 'Newfoundland dog'),  # index=257
    ('Great Pyrenees',),  # index=258
    ('Samoyed', 'Samoyede'),  # index=259
    ('Pomeranian',),  # index=260
    ('chow', 'chow chow'),  # index=261
    ('keeshond',),  # index=262
    ('Brabancon griffon',),  # index=263
    ('Pembroke', 'Pembroke Welsh corgi'),  # index=264
    ('Cardigan', 'Cardigan Welsh corgi'),  # index=265
    ('toy poodle',),  # index=266
    ('miniature poodle',),  # index=267
    ('standard poodle',),  # index=268
    ('Mexican hairless',),  # index=269
    ('timber wolf', 'grey wolf', 'gray wolf', 'Canis lupus'),  # index=270
    ('white wolf', 'Arctic wolf', 'Canis lupus tundrarum'),  # index=271
    ('red wolf', 'maned wolf', 'Canis rufus', 'Canis niger'),  # index=272
    ('coyote', 'prairie wolf', 'brush wolf', 'Canis latrans'),  # index=273
    ('dingo', 'warrigal', 'warragal', 'Canis dingo'),  # index=274
    ('dhole', 'Cuon alpinus'),  # index=275
    ('African hunting dog', 'hyena dog', 'Cape hunting dog',
     'Lycaon pictus'),  # index=276
    ('hyena', 'hyaena'),  # index=277
    ('red fox', 'Vulpes vulpes'),  # index=278
    ('kit fox', 'Vulpes macrotis'),  # index=279
    ('Arctic fox', 'white fox', 'Alopex lagopus'),  # index=280
    ('grey fox', 'gray fox', 'Urocyon cinereoargenteus'),  # index=281
    ('tabby', 'tabby cat'),  # index=282
    ('tiger cat',),  # index=283
    ('Persian cat',),  # index=284
    ('Siamese cat', 'Siamese'),  # index=285
    ('Egyptian cat',),  # index=286
    ('cougar', 'puma', 'catamount', 'mountain lion', 'painter', 'panther',
     'Felis concolor'),  # index=287
    ('lynx', 'catamount'),  # index=288
    ('leopard', 'Panthera pardus'),  # index=289
    ('snow leopard', 'ounce', 'Panthera uncia'),  # index=290
    ('jaguar', 'panther', 'Panthera onca', 'Felis onca'),  # index=291
    ('lion', 'king of beasts', 'Panthera leo'),  # index=292
    ('tiger', 'Panthera tigris'),  # index=293
    ('cheetah', 'chetah', 'Acinonyx jubatus'),  # index=294
    ('brown bear', 'bruin', 'Ursus arctos'),  # index=295
    ('American black bear', 'black bear', 'Ursus americanus',
     'Euarctos americanus'),  # index=296
    ('ice bear', 'polar bear', 'Ursus Maritimus',
     'Thalarctos maritimus'),  # index=297
    ('sloth bear', 'Melursus ursinus', 'Ursus ursinus'),  # index=298
    ('mongoose',),  # index=299
    ('meerkat', 'mierkat'),  # index=300
    ('tiger beetle',),  # index=301
    ('ladybug', 'ladybeetle', 'lady beetle', 'ladybird',
     'ladybird beetle'),  # index=302
    ('ground beetle', 'carabid beetle'),  # index=303
    ('long-horned beetle', 'longicorn', 'longicorn beetle'),  # index=304
    ('leaf beetle', 'chrysomelid'),  # index=305
    ('dung beetle',),  # index=306
    ('rhinoceros beetle',),  # index=307
    ('weevil',),  # index=308
    ('fly',),  # index=309
    ('bee',),  # index=310
    ('ant', 'emmet', 'pismire'),  # index=311
    ('grasshopper', 'hopper'),  # index=312
    ('cricket',),  # index=313
    ('walking stick', 'walkingstick', 'stick insect'),  # index=314
    ('cockroach', 'roach'),  # index=315
    ('mantis', 'mantid'),  # index=316
    ('cicada', 'cicala'),  # index=317
    ('leafhopper',),  # index=318
    ('lacewing', 'lacewing fly'),  # index=319
    ('dragonfly', 'darning needle', "devil's darning needle", 'sewing needle',
     'snake feeder', 'snake doctor', 'mosquito hawk',
     'skeeter hawk'),  # index=320
    ('damselfly',),  # index=321
    ('admiral',),  # index=322
    ('ringlet', 'ringlet butterfly'),  # index=323
    ('monarch', 'monarch butterfly', 'milkweed butterfly',
     'Danaus plexippus'),  # index=324
    ('cabbage butterfly',),  # index=325
    ('sulphur butterfly', 'sulfur butterfly'),  # index=326
    ('lycaenid', 'lycaenid butterfly'),  # index=327
    ('starfish', 'sea star'),  # index=328
    ('sea urchin',),  # index=329
    ('sea cucumber', 'holothurian'),  # index=330
    ('wood rabbit', 'cottontail', 'cottontail rabbit'),  # index=331
    ('hare',),  # index=332
    ('Angora', 'Angora rabbit'),  # index=333
    ('hamster',),  # index=334
    ('porcupine', 'hedgehog'),  # index=335
    ('fox squirrel', 'eastern fox squirrel', 'Sciurus niger'),  # index=336
    ('marmot',),  # index=337
    ('beaver',),  # index=338
    ('guinea pig', 'Cavia cobaya'),  # index=339
    ('sorrel',),  # index=340
    ('zebra',),  # index=341
    ('hog', 'pig', 'grunter', 'squealer', 'Sus scrofa'),  # index=342
    ('wild boar', 'boar', 'Sus scrofa'),  # index=343
    ('warthog',),  # index=344
    ('hippopotamus', 'hippo', 'river horse',
     'Hippopotamus amphibius'),  # index=345
    ('ox',),  # index=346
    ('water buffalo', 'water ox', 'Asiatic buffalo',
     'Bubalus bubalis'),  # index=347
    ('bison',),  # index=348
    ('ram', 'tup'),  # index=349
    ('bighorn', 'bighorn sheep', 'cimarron', 'Rocky Mountain bighorn',
     'Rocky Mountain sheep', 'Ovis canadensis'),  # index=350
    ('ibex', 'Capra ibex'),  # index=351
    ('hartebeest',),  # index=352
    ('impala', 'Aepyceros melampus'),  # index=353
    ('gazelle',),  # index=354
    ('Arabian camel', 'dromedary', 'Camelus dromedarius'),  # index=355
    ('llama',),  # index=356
    ('weasel',),  # index=357
    ('mink',),  # index=358
    ('polecat', 'fitch', 'foulmart', 'foumart',
     'Mustela putorius'),  # index=359
    ('black-footed ferret', 'ferret', 'Mustela nigripes'),  # index=360
    ('otter',),  # index=361
    ('skunk', 'polecat', 'wood pussy'),  # index=362
    ('badger',),  # index=363
    ('armadillo',),  # index=364
    ('three-toed sloth', 'ai', 'Bradypus tridactylus'),  # index=365
    ('orangutan', 'orang', 'orangutang', 'Pongo pygmaeus'),  # index=366
    ('gorilla', 'Gorilla gorilla'),  # index=367
    ('chimpanzee', 'chimp', 'Pan troglodytes'),  # index=368
    ('gibbon', 'Hylobates lar'),  # index=369
    ('siamang', 'Hylobates syndactylus',
     'Symphalangus syndactylus'),  # index=370
    ('guenon', 'guenon monkey'),  # index=371
    ('patas', 'hussar monkey', 'Erythrocebus patas'),  # index=372
    ('baboon',),  # index=373
    ('macaque',),  # index=374
    ('langur',),  # index=375
    ('colobus', 'colobus monkey'),  # index=376
    ('proboscis monkey', 'Nasalis larvatus'),  # index=377
    ('marmoset',),  # index=378
    ('capuchin', 'ringtail', 'Cebus capucinus'),  # index=379
    ('howler monkey', 'howler'),  # index=380
    ('titi', 'titi monkey'),  # index=381
    ('spider monkey', 'Ateles geoffroyi'),  # index=382
    ('squirrel monkey', 'Saimiri sciureus'),  # index=383
    ('Madagascar cat', 'ring-tailed lemur', 'Lemur catta'),  # index=384
    ('indri', 'indris', 'Indri indri', 'Indri brevicaudatus'),  # index=385
    ('Indian elephant', 'Elephas maximus'),  # index=386
    ('African elephant', 'Loxodonta africana'),  # index=387
    ('lesser panda', 'red panda', 'panda', 'bear cat', 'cat bear',
     'Ailurus fulgens'),  # index=388
    ('giant panda', 'panda', 'panda bear', 'coon bear',
     'Ailuropoda melanoleuca'),  # index=389
    ('barracouta', 'snoek'),  # index=390
    ('eel',),  # index=391
    ('coho', 'cohoe', 'coho salmon', 'blue jack', 'silver salmon',
     'Oncorhynchus kisutch'),  # index=392
    ('rock beauty', 'Holocanthus tricolor'),  # index=393
    ('anemone fish',),  # index=394
    ('sturgeon',),  # index=395
    ('gar', 'garfish', 'garpike', 'billfish',
     'Lepisosteus osseus'),  # index=396
    ('lionfish',),  # index=397
    ('puffer', 'pufferfish', 'blowfish', 'globefish'),  # index=398
    ('abacus',),  # index=399
    ('abaya',),  # index=400
    ('academic gown', 'academic robe', "judge's robe"),  # index=401
    ('accordion', 'piano accordion', 'squeeze box'),  # index=402
    ('acoustic guitar',),  # index=403
    ('aircraft carrier', 'carrier', 'flattop',
     'attack aircraft carrier'),  # index=404
    ('airliner',),  # index=405
    ('airship', 'dirigible'),  # index=406
    ('altar',),  # index=407
    ('ambulance',),  # index=408
    ('amphibian', 'amphibious vehicle'),  # index=409
    ('analog clock',),  # index=410
    ('apiary', 'bee house'),  # index=411
    ('apron',),  # index=412
    ('ashcan', 'trash can', 'garbage can', 'wastebin', 'ash bin', 'ash-bin',
     'ashbin', 'dustbin', 'trash barrel', 'trash bin'),  # index=413
    ('assault rifle', 'assault gun'),  # index=414
    ('backpack', 'back pack', 'knapsack', 'packsack', 'rucksack',
     'haversack'),  # index=415
    ('bakery', 'bakeshop', 'bakehouse'),  # index=416
    ('balance beam', 'beam'),  # index=417
    ('balloon',),  # index=418
    ('ballpoint', 'ballpoint pen', 'ballpen', 'Biro'),  # index=419
    ('Band Aid',),  # index=420
    ('banjo',),  # index=421
    ('bannister', 'banister', 'balustrade', 'balusters',
     'handrail'),  # index=422
    ('barbell',),  # index=423
    ('barber chair',),  # index=424
    ('barbershop',),  # index=425
    ('barn',),  # index=426
    ('barometer',),  # index=427
    ('barrel', 'cask'),  # index=428
    ('barrow', 'garden cart', 'lawn cart', 'wheelbarrow'),  # index=429
    ('baseball',),  # index=430
    ('basketball',),  # index=431
    ('bassinet',),  # index=432
    ('bassoon',),  # index=433
    ('bathing cap', 'swimming cap'),  # index=434
    ('bath towel',),  # index=435
    ('bathtub', 'bathing tub', 'bath', 'tub'),  # index=436
    ('beach wagon', 'station wagon', 'wagon', 'estate car', 'beach waggon',
     'station waggon', 'waggon'),  # index=437
    ('beacon', 'lighthouse', 'beacon light', 'pharos'),  # index=438
    ('beaker',),  # index=439
    ('bearskin', 'busby', 'shako'),  # index=440
    ('beer bottle',),  # index=441
    ('beer glass',),  # index=442
    ('bell cote', 'bell cot'),  # index=443
    ('bib',),  # index=444
    ('bicycle-built-for-two', 'tandem bicycle', 'tandem'),  # index=445
    ('bikini', 'two-piece'),  # index=446
    ('binder', 'ring-binder'),  # index=447
    ('binoculars', 'field glasses', 'opera glasses'),  # index=448
    ('birdhouse',),  # index=449
    ('boathouse',),  # index=450
    ('bobsled', 'bobsleigh', 'bob'),  # index=451
    ('bolo tie', 'bolo', 'bola tie', 'bola'),  # index=452
    ('bonnet', 'poke bonnet'),  # index=453
    ('bookcase',),  # index=454
    ('bookshop', 'bookstore', 'bookstall'),  # index=455
    ('bottlecap',),  # index=456
    ('bow',),  # index=457
    ('bow tie', 'bow-tie', 'bowtie'),  # index=458
    ('brass', 'memorial tablet', 'plaque'),  # index=459
    ('brassiere', 'bra', 'bandeau'),  # index=460
    ('breakwater', 'groin', 'groyne', 'mole', 'bulwark', 'seawall',
     'jetty'),  # index=461
    ('breastplate', 'aegis', 'egis'),  # index=462
    ('broom',),  # index=463
    ('bucket', 'pail'),  # index=464
    ('buckle',),  # index=465
    ('bulletproof vest',),  # index=466
    ('bullet train', 'bullet'),  # index=467
    ('butcher shop', 'meat market'),  # index=468
    ('cab', 'hack', 'taxi', 'taxicab'),  # index=469
    ('caldron', 'cauldron'),  # index=470
    ('candle', 'taper', 'wax light'),  # index=471
    ('cannon',),  # index=472
    ('canoe',),  # index=473
    ('can opener', 'tin opener'),  # index=474
    ('cardigan',),  # index=475
    ('car mirror',),  # index=476
    ('carousel', 'carrousel', 'merry-go-round', 'roundabout',
     'whirligig'),  # index=477
    ("carpenter's kit", 'tool kit'),  # index=478
    ('carton',),  # index=479
    ('car wheel',),  # index=480
    ('cash machine', 'cash dispenser', 'automated teller machine',
     'automatic teller machine', 'automated teller', 'automatic teller',
     'ATM'),  # index=481
    ('cassette',),  # index=482
    ('cassette player',),  # index=483
    ('castle',),  # index=484
    ('catamaran',),  # index=485
    ('CD player',),  # index=486
    ('cello', 'violoncello'),  # index=487
    ('cellular telephone', 'cellular phone', 'cellphone', 'cell',
     'mobile phone'),  # index=488
    ('chain',),  # index=489
    ('chainlink fence',),  # index=490
    ('chain mail', 'ring mail', 'mail', 'chain armor', 'chain armour',
     'ring armor', 'ring armour'),  # index=491
    ('chain saw', 'chainsaw'),  # index=492
    ('chest',),  # index=493
    ('chiffonier', 'commode'),  # index=494
    ('chime', 'bell', 'gong'),  # index=495
    ('china cabinet', 'china closet'),  # index=496
    ('Christmas stocking',),  # index=497
    ('church', 'church building'),  # index=498
    ('cinema', 'movie theater', 'movie theatre', 'movie house',
     'picture palace'),  # index=499
    ('cleaver', 'meat cleaver', 'chopper'),  # index=500
    ('cliff dwelling',),  # index=501
    ('cloak',),  # index=502
    ('clog', 'geta', 'patten', 'sabot'),  # index=503
    ('cocktail shaker',),  # index=504
    ('coffee mug',),  # index=505
    ('coffeepot',),  # index=506
    ('coil', 'spiral', 'volute', 'whorl', 'helix'),  # index=507
    ('combination lock',),  # index=508
    ('computer keyboard', 'keypad'),  # index=509
    ('confectionery', 'confectionary', 'candy store'),  # index=510
    ('container ship', 'containership', 'container vessel'),  # index=511
    ('convertible',),  # index=512
    ('corkscrew', 'bottle screw'),  # index=513
    ('cornet', 'horn', 'trumpet', 'trump'),  # index=514
    ('cowboy boot',),  # index=515
    ('cowboy hat', 'ten-gallon hat'),  # index=516
    ('cradle',),  # index=517
    ('crane',),  # index=518
    ('crash helmet',),  # index=519
    ('crate',),  # index=520
    ('crib', 'cot'),  # index=521
    ('Crock Pot',),  # index=522
    ('croquet ball',),  # index=523
    ('crutch',),  # index=524
    ('cuirass',),  # index=525
    ('dam', 'dike', 'dyke'),  # index=526
    ('desk',),  # index=527
    ('desktop computer',),  # index=528
    ('dial telephone', 'dial phone'),  # index=529
    ('diaper', 'nappy', 'napkin'),  # index=530
    ('digital clock',),  # index=531
    ('digital watch',),  # index=532
    ('dining table', 'board'),  # index=533
    ('dishrag', 'dishcloth'),  # index=534
    ('dishwasher', 'dish washer', 'dishwashing machine'),  # index=535
    ('disk brake', 'disc brake'),  # index=536
    ('dock', 'dockage', 'docking facility'),  # index=537
    ('dogsled', 'dog sled', 'dog sleigh'),  # index=538
    ('dome',),  # index=539
    ('doormat', 'welcome mat'),  # index=540
    ('drilling platform', 'offshore rig'),  # index=541
    ('drum', 'membranophone', 'tympan'),  # index=542
    ('drumstick',),  # index=543
    ('dumbbell',),  # index=544
    ('Dutch oven',),  # index=545
    ('electric fan', 'blower'),  # index=546
    ('electric guitar',),  # index=547
    ('electric locomotive',),  # index=548
    ('entertainment center',),  # index=549
    ('envelope',),  # index=550
    ('espresso maker',),  # index=551
    ('face powder',),  # index=552
    ('feather boa', 'boa'),  # index=553
    ('file', 'file cabinet', 'filing cabinet'),  # index=554
    ('fireboat',),  # index=555
    ('fire engine', 'fire truck'),  # index=556
    ('fire screen', 'fireguard'),  # index=557
    ('flagpole', 'flagstaff'),  # index=558
    ('flute', 'transverse flute'),  # index=559
    ('folding chair',),  # index=560
    ('football helmet',),  # index=561
    ('forklift',),  # index=562
    ('fountain',),  # index=563
    ('fountain pen',),  # index=564
    ('four-poster',),  # index=565
    ('freight car',),  # index=566
    ('French horn', 'horn'),  # index=567
    ('frying pan', 'frypan', 'skillet'),  # index=568
    ('fur coat',),  # index=569
    ('garbage truck', 'dustcart'),  # index=570
    ('gasmask', 'respirator', 'gas helmet'),  # index=571
    ('gas pump', 'gasoline pump', 'petrol pump',
     'island dispenser'),  # index=572
    ('goblet',),  # index=573
    ('go-kart',),  # index=574
    ('golf ball',),  # index=575
    ('golfcart', 'golf cart'),  # index=576
    ('gondola',),  # index=577
    ('gong', 'tam-tam'),  # index=578
    ('gown',),  # index=579
    ('grand piano', 'grand'),  # index=580
    ('greenhouse', 'nursery', 'glasshouse'),  # index=581
    ('grille', 'radiator grille'),  # index=582
    ('grocery store', 'grocery', 'food market', 'market'),  # index=583
    ('guillotine',),  # index=584
    ('hair slide',),  # index=585
    ('hair spray',),  # index=586
    ('half track',),  # index=587
    ('hammer',),  # index=588
    ('hamper',),  # index=589
    ('hand blower', 'blow dryer', 'blow drier', 'hair dryer',
     'hair drier'),  # index=590
    ('hand-held computer', 'hand-held microcomputer'),  # index=591
    ('handkerchief', 'hankie', 'hanky', 'hankey'),  # index=592
    ('hard disc', 'hard disk', 'fixed disk'),  # index=593
    ('harmonica', 'mouth organ', 'harp', 'mouth harp'),  # index=594
    ('harp',),  # index=595
    ('harvester', 'reaper'),  # index=596
    ('hatchet',),  # index=597
    ('holster',),  # index=598
    ('home theater', 'home theatre'),  # index=599
    ('honeycomb',),  # index=600
    ('hook', 'claw'),  # index=601
    ('hoopskirt', 'crinoline'),  # index=602
    ('horizontal bar', 'high bar'),  # index=603
    ('horse cart', 'horse-cart'),  # index=604
    ('hourglass',),  # index=605
    ('iPod',),  # index=606
    ('iron', 'smoothing iron'),  # index=607
    ("jack-o'-lantern",),  # index=608
    ('jean', 'blue jean', 'denim'),  # index=609
    ('jeep', 'landrover'),  # index=610
    ('jersey', 'T-shirt', 'tee shirt'),  # index=611
    ('jigsaw puzzle',),  # index=612
    ('jinrikisha', 'ricksha', 'rickshaw'),  # index=613
    ('joystick',),  # index=614
    ('kimono',),  # index=615
    ('knee pad',),  # index=616
    ('knot',),  # index=617
    ('lab coat', 'laboratory coat'),  # index=618
    ('ladle',),  # index=619
    ('lampshade', 'lamp shade'),  # index=620
    ('laptop', 'laptop computer'),  # index=621
    ('lawn mower', 'mower'),  # index=622
    ('lens cap', 'lens cover'),  # index=623
    ('letter opener', 'paper knife', 'paperknife'),  # index=624
    ('library',),  # index=625
    ('lifeboat',),  # index=626
    ('lighter', 'light', 'igniter', 'ignitor'),  # index=627
    ('limousine', 'limo'),  # index=628
    ('liner', 'ocean liner'),  # index=629
    ('lipstick', 'lip rouge'),  # index=630
    ('Loafer',),  # index=631
    ('lotion',),  # index=632
    ('loudspeaker', 'speaker', 'speaker unit', 'loudspeaker system',
     'speaker system'),  # index=633
    ('loupe', "jeweler's loupe"),  # index=634
    ('lumbermill', 'sawmill'),  # index=635
    ('magnetic compass',),  # index=636
    ('mailbag', 'postbag'),  # index=637
    ('mailbox', 'letter box'),  # index=638
    ('maillot',),  # index=639
    ('maillot', 'tank suit'),  # index=640
    ('manhole cover',),  # index=641
    ('maraca',),  # index=642
    ('marimba', 'xylophone'),  # index=643
    ('mask',),  # index=644
    ('matchstick',),  # index=645
    ('maypole',),  # index=646
    ('maze', 'labyrinth'),  # index=647
    ('measuring cup',),  # index=648
    ('medicine chest', 'medicine cabinet'),  # index=649
    ('megalith', 'megalithic structure'),  # index=650
    ('microphone', 'mike'),  # index=651
    ('microwave', 'microwave oven'),  # index=652
    ('military uniform',),  # index=653
    ('milk can',),  # index=654
    ('minibus',),  # index=655
    ('miniskirt', 'mini'),  # index=656
    ('minivan',),  # index=657
    ('missile',),  # index=658
    ('mitten',),  # index=659
    ('mixing bowl',),  # index=660
    ('mobile home', 'manufactured home'),  # index=661
    ('Model T',),  # index=662
    ('modem',),  # index=663
    ('monastery',),  # index=664
    ('monitor',),  # index=665
    ('moped',),  # index=666
    ('mortar',),  # index=667
    ('mortarboard',),  # index=668
    ('mosque',),  # index=669
    ('mosquito net',),  # index=670
    ('motor scooter', 'scooter'),  # index=671
    ('mountain bike', 'all-terrain bike', 'off-roader'),  # index=672
    ('mountain tent',),  # index=673
    ('mouse', 'computer mouse'),  # index=674
    ('mousetrap',),  # index=675
    ('moving van',),  # index=676
    ('muzzle',),  # index=677
    ('nail',),  # index=678
    ('neck brace',),  # index=679
    ('necklace',),  # index=680
    ('nipple',),  # index=681
    ('notebook', 'notebook computer'),  # index=682
    ('obelisk',),  # index=683
    ('oboe', 'hautboy', 'hautbois'),  # index=684
    ('ocarina', 'sweet potato'),  # index=685
    ('odometer', 'hodometer', 'mileometer', 'milometer'),  # index=686
    ('oil filter',),  # index=687
    ('organ', 'pipe organ'),  # index=688
    ('oscilloscope', 'scope', 'cathode-ray oscilloscope', 'CRO'),  # index=689
    ('overskirt',),  # index=690
    ('oxcart',),  # index=691
    ('oxygen mask',),  # index=692
    ('packet',),  # index=693
    ('paddle', 'boat paddle'),  # index=694
    ('paddlewheel', 'paddle wheel'),  # index=695
    ('padlock',),  # index=696
    ('paintbrush',),  # index=697
    ('pajama', 'pyjama', "pj's", 'jammies'),  # index=698
    ('palace',),  # index=699
    ('panpipe', 'pandean pipe', 'syrinx'),  # index=700
    ('paper towel',),  # index=701
    ('parachute', 'chute'),  # index=702
    ('parallel bars', 'bars'),  # index=703
    ('park bench',),  # index=704
    ('parking meter',),  # index=705
    ('passenger car', 'coach', 'carriage'),  # index=706
    ('patio', 'terrace'),  # index=707
    ('pay-phone', 'pay-station'),  # index=708
    ('pedestal', 'plinth', 'footstall'),  # index=709
    ('pencil box', 'pencil case'),  # index=710
    ('pencil sharpener',),  # index=711
    ('perfume', 'essence'),  # index=712
    ('Petri dish',),  # index=713
    ('photocopier',),  # index=714
    ('pick', 'plectrum', 'plectron'),  # index=715
    ('pickelhaube',),  # index=716
    ('picket fence', 'paling'),  # index=717
    ('pickup', 'pickup truck'),  # index=718
    ('pier',),  # index=719
    ('piggy bank', 'penny bank'),  # index=720
    ('pill bottle',),  # index=721
    ('pillow',),  # index=722
    ('ping-pong ball',),  # index=723
    ('pinwheel',),  # index=724
    ('pirate', 'pirate ship'),  # index=725
    ('pitcher', 'ewer'),  # index=726
    ('plane', "carpenter's plane", 'woodworking plane'),  # index=727
    ('planetarium',),  # index=728
    ('plastic bag',),  # index=729
    ('plate rack',),  # index=730
    ('plow', 'plough'),  # index=731
    ('plunger', "plumber's helper"),  # index=732
    ('Polaroid camera', 'Polaroid Land camera'),  # index=733
    ('pole',),  # index=734
    ('police van', 'police wagon', 'paddy wagon', 'patrol wagon', 'wagon',
     'black Maria'),  # index=735
    ('poncho',),  # index=736
    ('pool table', 'billiard table', 'snooker table'),  # index=737
    ('pop bottle', 'soda bottle'),  # index=738
    ('pot', 'flowerpot'),  # index=739
    ("potter's wheel",),  # index=740
    ('power drill',),  # index=741
    ('prayer rug', 'prayer mat'),  # index=742
    ('printer',),  # index=743
    ('prison', 'prison house'),  # index=744
    ('projectile', 'missile'),  # index=745
    ('projector',),  # index=746
    ('puck', 'hockey puck'),  # index=747
    ('punching bag', 'punch bag', 'punching ball', 'punchball'),  # index=748
    ('purse',),  # index=749
    ('quill', 'quill pen'),  # index=750
    ('quilt', 'comforter', 'comfort', 'puff'),  # index=751
    ('racer', 'race car', 'racing car'),  # index=752
    ('racket', 'racquet'),  # index=753
    ('radiator',),  # index=754
    ('radio', 'wireless'),  # index=755
    ('radio telescope', 'radio reflector'),  # index=756
    ('rain barrel',),  # index=757
    ('recreational vehicle', 'RV', 'R.V.'),  # index=758
    ('reel',),  # index=759
    ('reflex camera',),  # index=760
    ('refrigerator', 'icebox'),  # index=761
    ('remote control', 'remote'),  # index=762
    ('restaurant', 'eating house', 'eating place', 'eatery'),  # index=763
    ('revolver', 'six-gun', 'six-shooter'),  # index=764
    ('rifle',),  # index=765
    ('rocking chair', 'rocker'),  # index=766
    ('rotisserie',),  # index=767
    ('rubber eraser', 'rubber', 'pencil eraser'),  # index=768
    ('rugby ball',),  # index=769
    ('rule', 'ruler'),  # index=770
    ('running shoe',),  # index=771
    ('safe',),  # index=772
    ('safety pin',),  # index=773
    ('saltshaker', 'salt shaker'),  # index=774
    ('sandal',),  # index=775
    ('sarong',),  # index=776
    ('sax', 'saxophone'),  # index=777
    ('scabbard',),  # index=778
    ('scale', 'weighing machine'),  # index=779
    ('school bus',),  # index=780
    ('schooner',),  # index=781
    ('scoreboard',),  # index=782
    ('screen', 'CRT screen'),  # index=783
    ('screw',),  # index=784
    ('screwdriver',),  # index=785
    ('seat belt', 'seatbelt'),  # index=786
    ('sewing machine',),  # index=787
    ('shield', 'buckler'),  # index=788
    ('shoe shop', 'shoe-shop', 'shoe store'),  # index=789
    ('shoji',),  # index=790
    ('shopping basket',),  # index=791
    ('shopping cart',),  # index=792
    ('shovel',),  # index=793
    ('shower cap',),  # index=794
    ('shower curtain',),  # index=795
    ('ski',),  # index=796
    ('ski mask',),  # index=797
    ('sleeping bag',),  # index=798
    ('slide rule', 'slipstick'),  # index=799
    ('sliding door',),  # index=800
    ('slot', 'one-armed bandit'),  # index=801
    ('snorkel',),  # index=802
    ('snowmobile',),  # index=803
    ('snowplow', 'snowplough'),  # index=804
    ('soap dispenser',),  # index=805
    ('soccer ball',),  # index=806
    ('sock',),  # index=807
    ('solar dish', 'solar collector', 'solar furnace'),  # index=808
    ('sombrero',),  # index=809
    ('soup bowl',),  # index=810
    ('space bar',),  # index=811
    ('space heater',),  # index=812
    ('space shuttle',),  # index=813
    ('spatula',),  # index=814
    ('speedboat',),  # index=815
    ('spider web', "spider's web"),  # index=816
    ('spindle',),  # index=817
    ('sports car', 'sport car'),  # index=818
    ('spotlight', 'spot'),  # index=819
    ('stage',),  # index=820
    ('steam locomotive',),  # index=821
    ('steel arch bridge',),  # index=822
    ('steel drum',),  # index=823
    ('stethoscope',),  # index=824
    ('stole',),  # index=825
    ('stone wall',),  # index=826
    ('stopwatch', 'stop watch'),  # index=827
    ('stove',),  # index=828
    ('strainer',),  # index=829
    ('streetcar', 'tram', 'tramcar', 'trolley', 'trolley car'),  # index=830
    ('stretcher',),  # index=831
    ('studio couch', 'day bed'),  # index=832
    ('stupa', 'tope'),  # index=833
    ('submarine', 'pigboat', 'sub', 'U-boat'),  # index=834
    ('suit', 'suit of clothes'),  # index=835
    ('sundial',),  # index=836
    ('sunglass',),  # index=837
    ('sunglasses', 'dark glasses', 'shades'),  # index=838
    ('sunscreen', 'sunblock', 'sun blocker'),  # index=839
    ('suspension bridge',),  # index=840
    ('swab', 'swob', 'mop'),  # index=841
    ('sweatshirt',),  # index=842
    ('swimming trunks', 'bathing trunks'),  # index=843
    ('swing',),  # index=844
    ('switch', 'electric switch', 'electrical switch'),  # index=845
    ('syringe',),  # index=846
    ('table lamp',),  # index=847
    ('tank', 'army tank', 'armored combat vehicle',
     'armoured combat vehicle'),  # index=848
    ('tape player',),  # index=849
    ('teapot',),  # index=850
    ('teddy', 'teddy bear'),  # index=851
    ('television', 'television system'),  # index=852
    ('tennis ball',),  # index=853
    ('thatch', 'thatched roof'),  # index=854
    ('theater curtain', 'theatre curtain'),  # index=855
    ('thimble',),  # index=856
    ('thresher', 'thrasher', 'threshing machine'),  # index=857
    ('throne',),  # index=858
    ('tile roof',),  # index=859
    ('toaster',),  # index=860
    ('tobacco shop', 'tobacconist shop', 'tobacconist'),  # index=861
    ('toilet seat',),  # index=862
    ('torch',),  # index=863
    ('totem pole',),  # index=864
    ('tow truck', 'tow car', 'wrecker'),  # index=865
    ('toyshop',),  # index=866
    ('tractor',),  # index=867
    ('trailer truck', 'tractor trailer', 'trucking rig', 'rig',
     'articulated lorry', 'semi'),  # index=868
    ('tray',),  # index=869
    ('trench coat',),  # index=870
    ('tricycle', 'trike', 'velocipede'),  # index=871
    ('trimaran',),  # index=872
    ('tripod',),  # index=873
    ('triumphal arch',),  # index=874
    ('trolleybus', 'trolley coach', 'trackless trolley'),  # index=875
    ('trombone',),  # index=876
    ('tub', 'vat'),  # index=877
    ('turnstile',),  # index=878
    ('typewriter keyboard',),  # index=879
    ('umbrella',),  # index=880
    ('unicycle', 'monocycle'),  # index=881
    ('upright', 'upright piano'),  # index=882
    ('vacuum', 'vacuum cleaner'),  # index=883
    ('vase',),  # index=884
    ('vault',),  # index=885
    ('velvet',),  # index=886
    ('vending machine',),  # index=887
    ('vestment',),  # index=888
    ('viaduct',),  # index=889
    ('violin', 'fiddle'),  # index=890
    ('volleyball',),  # index=891
    ('waffle iron',),  # index=892
    ('wall clock',),  # index=893
    ('wallet', 'billfold', 'notecase', 'pocketbook'),  # index=894
    ('wardrobe', 'closet', 'press'),  # index=895
    ('warplane', 'military plane'),  # index=896
    ('washbasin', 'handbasin', 'washbowl', 'lavabo',
     'wash-hand basin'),  # index=897
    ('washer', 'automatic washer', 'washing machine'),  # index=898
    ('water bottle',),  # index=899
    ('water jug',),  # index=900
    ('water tower',),  # index=901
    ('whiskey jug',),  # index=902
    ('whistle',),  # index=903
    ('wig',),  # index=904
    ('window screen',),  # index=905
    ('window shade',),  # index=906
    ('Windsor tie',),  # index=907
    ('wine bottle',),  # index=908
    ('wing',),  # index=909
    ('wok',),  # index=910
    ('wooden spoon',),  # index=911
    ('wool', 'woolen', 'woollen'),  # index=912
    ('worm fence', 'snake fence', 'snake-rail fence',
     'Virginia fence'),  # index=913
    ('wreck',),  # index=914
    ('yawl',),  # index=915
    ('yurt',),  # index=916
    ('web site', 'website', 'internet site', 'site'),  # index=917
    ('comic book',),  # index=918
    ('crossword puzzle', 'crossword'),  # index=919
    ('street sign',),  # index=920
    ('traffic light', 'traffic signal', 'stoplight'),  # index=921
    ('book jacket', 'dust cover', 'dust jacket', 'dust wrapper'),  # index=922
    ('menu',),  # index=923
    ('plate',),  # index=924
    ('guacamole',),  # index=925
    ('consomme',),  # index=926
    ('hot pot', 'hotpot'),  # index=927
    ('trifle',),  # index=928
    ('ice cream', 'icecream'),  # index=929
    ('ice lolly', 'lolly', 'lollipop', 'popsicle'),  # index=930
    ('French loaf',),  # index=931
    ('bagel', 'beigel'),  # index=932
    ('pretzel',),  # index=933
    ('cheeseburger',),  # index=934
    ('hotdog', 'hot dog', 'red hot'),  # index=935
    ('mashed potato',),  # index=936
    ('head cabbage',),  # index=937
    ('broccoli',),  # index=938
    ('cauliflower',),  # index=939
    ('zucchini', 'courgette'),  # index=940
    ('spaghetti squash',),  # index=941
    ('acorn squash',),  # index=942
    ('butternut squash',),  # index=943
    ('cucumber', 'cuke'),  # index=944
    ('artichoke', 'globe artichoke'),  # index=945
    ('bell pepper',),  # index=946
    ('cardoon',),  # index=947
    ('mushroom',),  # index=948
    ('Granny Smith',),  # index=949
    ('strawberry',),  # index=950
    ('orange',),  # index=951
    ('lemon',),  # index=952
    ('fig',),  # index=953
    ('pineapple', 'ananas'),  # index=954
    ('banana',),  # index=955
    ('jackfruit', 'jak', 'jack'),  # index=956
    ('custard apple',),  # index=957
    ('pomegranate',),  # index=958
    ('hay',),  # index=959
    ('carbonara',),  # index=960
    ('chocolate sauce', 'chocolate syrup'),  # index=961
    ('dough',),  # index=962
    ('meat loaf', 'meatloaf'),  # index=963
    ('pizza', 'pizza pie'),  # index=964
    ('potpie',),  # index=965
    ('burrito',),  # index=966
    ('red wine',),  # index=967
    ('espresso',),  # index=968
    ('cup',),  # index=969
    ('eggnog',),  # index=970
    ('alp',),  # index=971
    ('bubble',),  # index=972
    ('cliff', 'drop', 'drop-off'),  # index=973
    ('coral reef',),  # index=974
    ('geyser',),  # index=975
    ('lakeside', 'lakeshore'),  # index=976
    ('promontory', 'headland', 'head', 'foreland'),  # index=977
    ('sandbar', 'sand bar'),  # index=978
    ('seashore', 'coast', 'seacoast', 'sea-coast'),  # index=979
    ('valley', 'vale'),  # index=980
    ('volcano',),  # index=981
    ('ballplayer', 'baseball player'),  # index=982
    ('groom', 'bridegroom'),  # index=983
    ('scuba diver',),  # index=984
    ('rapeseed',),  # index=985
    ('daisy',),  # index=986
    ("yellow lady's slipper", 'yellow lady-slipper', 'Cypripedium calceolus',
     'Cypripedium parviflorum'),  # index=987
    ('corn',),  # index=988
    ('acorn',),  # index=989
    ('hip', 'rose hip', 'rosehip'),  # index=990
    ('buckeye', 'horse chestnut', 'conker'),  # index=991
    ('coral fungus',),  # index=992
    ('agaric',),  # index=993
    ('gyromitra',),  # index=994
    ('stinkhorn', 'carrion fungus'),  # index=995
    ('earthstar',),  # index=996
    ('hen-of-the-woods', 'hen of the woods', 'Polyporus frondosus',
     'Grifola frondosa'),  # index=997
    ('bolete',),  # index=998
    ('ear', 'spike', 'capitulum'),  # index=999
    ('toilet tissue', 'toilet paper', 'bathroom tissue'),  # index=1000
)
