#!/bin/bash

#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    configure)
        if [ -z "$2" ]; then
            dtc -W no-unit_address_vs_reg -@ -O dtb -o /boot/overlays/aiy-visionbonnet.dtbo \
                /opt/aiy/overlay-vision/aiy-visionbonnet-overlay.dts
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
