#!/bin/bash

set -e

git clone /opt/aiy/projects-python.bundle /opt/aiy/projects-python

pushd /opt/aiy/projects-python
git checkout aiy-github
git tag -d aiy-github
git checkout -b aiyprojects
git remote remove origin
git remote add origin https://github.com/google/aiyprojects-raspbian
git config branch.aiyprojects.remote origin
git config branch.aiyprojects.merge refs/heads/aiyprojects
popd

chown -R pi:pi /opt/aiy/projects-python
pip3 install --no-deps -e /opt/aiy/projects-python/src
